### ISSUE TITLE
ttl formatting not respecting comments in blank nodes. 

### ISSUE THREAD

**Issue by somanythings** [lunisolar/LNKD.tech-Editor#4] opened 2021-02-05 09:37 UTC
if i have something like this: 

```ttl
<some-iri>
  with:aPredicateToBlankNode [ a                :BlankNode ;
#                               some:commentedPO :commented 
                             ] ;
```

after applying formatting, i get
```ttl
<some-iri>
  with:aPredicateToBlankNode [ a :BlankNode ;
                             #                               some:commentedPO :commented  ] ;
```
so the closing ]; is pulled up, behind the comment, breaking the file.

**Comment by lunisolar** [comment] 2021-02-08 17:35
I see two issues with how plugin handled the comment in that fragment. 

1. The  inclusion of the next line - closing bracket. 
2. The indent adjustment of the comment- It should not change.

I will try to investigate during the week how the fix looks like.

**Comment by lunisolar** [comment] 2021-02-18 15:53
Due to the issues in other project I need to park this issue for few weeks.

**Comment by lunisolar** [comment] 2021-04-12 14:31
*At. 1*
Fixed . Also fixed for lists: ( object+   )       - the same issue. 

*At 2.*
Formatting now will detect if comment starts at the beginning of a line (usually a effect of commenting a line by  Ctrl-/  ) and does not indent such comment.  Otherwise the comment is indented as usual. 
I wanted reproduce here similar behavior to Java. 

Will be part of next release.

**Closed as completed** 2021-04-12 14:51 UTC
